import Head from "next/head";
import { Container } from "@styles/container";
// Data
import { tags } from "@data/tags";
import { projects } from "@data/projects";
import { hobbies } from "@data/hobbies";
import { certificates } from "@data/certificates";
// Components
import { Hero } from "@components/hero";
import { ProfileSkills } from "@components/profileSkills";
import { Profile } from "@components/profile";
import { Skills } from "@components/skills";
import { Projects } from "@components/projects";
import { Hobbies } from "@components/hobbies";
import { Certificates } from "@components/certificates";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Hero title="My Portfolio" subTitle="By gbdeveloper"></Hero>
        <ProfileSkills>
          <Profile />
          <Skills />
        </ProfileSkills>
        <Projects projects={projects} tags={tags} />
        <Hobbies hobbies={hobbies} />
        <Certificates certificates={certificates} />
      </Container>
    </div>
  );
};

export default Home;
